---
- hosts: server
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm

    - name: Create a directory 
      file:
        path: /var/www/DevOps_Project
        state: directory
        owner: azureuser
        group: azureuser

    - name: Copy the Node.js application code
      copy:
        src: ./DevOps_Project/  # Replace with your app directory
        dest: /var/www/DevOps_Project/
        owner: azureuser
        group: azureuser

    - name: Install Node.js dependencies
      npm:
        path: /var/www/DevOps_Project/
        production: yes  

    - name: Start the Node.js application
      command: npm start
      args:
        chdir: /var/www/DevOps_Project/
      environment:
        NODE_ENV: production
